### ISSUE TITLE
Nothing happens when entering Music & Sounds GUI

### ISSUE THREAD

**Issue by Scheigster** [srsCode/ReOpenAL#1]
* **Modpack**: FTB Sky Odyssey 1.0

* **Minecraft version**: 1.12

* **Issue**: 

Hello,

I'm not sure wether this is the mod not working or me not understanding what it should do.

I'm having that annoying issue where I need to reload the game or the resource pack whenever I want to switch default audio device (so basically whenever I plug/unplug my headset). Is this what your mod should fix ?

As of right now, nothing happens when I enter the sound GUI.

Thanks in advance for your clarifications and for your work on the mod.

**Comment by srs-bsns** [comment]
ReOpenAL is meant to be a remedy for the very specific issue of the OpenAL sound system not properly initialising during start-up (silent mode). Upon entering the sound options GUI, ReOpenAL checks to see that the OpenAL sound library is the active library, and if it is not it restarts the sound system with the OpenAL library.

In your case it is highly likely that OpenAL *is* initialised properly, but only the output device is changed, so ReOpenAL does nothing. This issue of changing output devices only came to my attention after I had released ReOpenAL, so I did not add a means to manually restart the sound system, though I may add one in the future.

If you want, you can check out [RandomTweaks](https://minecraft.curseforge.com/projects/randomtweaks) which has a means to manually restart the sound system (key bind).
